namespace Pacman.Models
{
    public class Map
    {
        public Element[,] Elements = new Element[30, 22];

        public Map()
        {
            Elements = new Element[,] {
                   { Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall },
                   { Element.Wall,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Wall },
                   { Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall },
                   { Element.Wall,Element.SuperCoin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.SuperCoin,Element.Wall },
                   { Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall },
                   { Element.Wall,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Wall },
                   { Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall },
                   { Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall },
                   { Element.Wall,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Wall },
                   { Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.EmptyField,Element.EmptyField,Element.EmptyField,Element.EmptyField,Element.EmptyField,Element.EmptyField,Element.EmptyField,Element.EmptyField,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall },
                   { Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Ghost,Element.Ghost,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall },
                   { Element.EmptyField,Element.EmptyField,Element.EmptyField,Element.EmptyField,Element.EmptyField,Element.EmptyField,Element.Coin,Element.EmptyField,Element.EmptyField,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Ghost,Element.Ghost,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.EmptyField,Element.EmptyField,Element.Coin,Element.EmptyField,Element.EmptyField,Element.EmptyField,Element.EmptyField,Element.EmptyField,Element.EmptyField },
                   { Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall },
                   { Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall },
                   { Element.Wall,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.RightPacman,Element.Coin,Element.Coin,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Wall },
                   { Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall },
                   { Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall },
                   { Element.Wall,Element.SuperCoin,Element.Coin,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Coin,Element.SuperCoin,Element.Wall },
                   { Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall },
                   { Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall },
                   { Element.Wall,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Wall },
                   { Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall },
                   { Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Coin,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Coin,Element.Wall },
                   { Element.Wall,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Coin,Element.Wall },
                   { Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall,Element.Wall } };

        }
    }
}
